### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/KeywordCalls.jl#11]
@simonbyrne suggested a nice benchmark for this [here](https://discourse.julialang.org/t/ann-keywordcalls-jl/60266/7?u=cscherrer). I think this is a little harder to optimize than what we were previously doing, and it looks like we've had a small performance regression:
```julia
using KeywordCalls

function fib_kc((n,f0)::NamedTuple{(:n, :f0)})
    if n <= 1
        return f0
    end
    fib_kc((f0=f0, n=n-1)) + fib_kc((f0=f0,n=n-2))
end
@kwcall fib_kc(n, f0)


using BenchmarkTools
@btime $fib_kc((n=30,f0=1))


# master:
# julia> @btime $fib_kc((n=30,f0=1))
#   26.479 ms (0 allocations: 0 bytes)
# 1346269

# pr/rfourquet/6:
# julia> @btime $fib_kc((n=30,f0=1))
#   20.585 ms (0 allocations: 0 bytes)
# 1346269
```

This is a little different than what Simon suggested, and stresses the code by making recursive calls in the "wrong" order.

I really like how clean the current code is, but it's hard to turn down some extra performance. And I think we'll need type-level tricks from GeneralizedGenerated to efficiently handle aliases anyway (see https://github.com/cscherrer/KeywordCalls.jl/issues/10).

What do you think @simeonschaub @rfourquet ?

**Comment by cscherrer** [comment]
With https://github.com/cscherrer/KeywordCalls.jl/commit/7ef86a495c44be08999c91f6f51a38266f9d2384, this has gotten worse. It may be helpful to give a short overview of the history, and how the current difficulty fits into this.

In the original approach, I had a `baseperm` dictionary in the `KeywordCalls` module that started out empty. The idea was that indexing `baseperm[(f, sortedkeys)]` would return the "preferred ordering" for those keys. You can always sort things, so the solution becomes a sort followed by a lookup, and it's all done at compile time.

This worked great, except for some precompilation problems. @rfourquet had a very slick solution for this, and also added some nice tests.

@simeonschaub was also looking into the problem, and came up with an approach that's much more elegant than what I had been doing. This is the version 1.3 approach.

That's great, but now we want to add default values (thanks @mileslucas for this idea and implementation) and aliases (@icweaver I think you brought this up, thanks). So the process is now

1. Map key names to their alias
2. Merge with defaults
3. Put things in order

Since NamedTuples are typed by their keys, step (1) changes the types, and exactly how it does this isn't known until runtime. So the result still works, but it becomes a dynamic dispatch, so it's much slower.

The best approach I can see is to go back to the previous approach, basically https://github.com/cscherrer/KeywordCalls.jl/pull/6, and build the default value and alias support in the same way. I think this ought to get us to a point of all three steps working at compile time, so the only runtime cost is the permutation of the values. Which permutation is needed can be determined at compile time, so I think all of this can be very fast.

Any thoughts? Sound like a reasonable approach? 

EDIT: I should probably link this: https://github.com/JuliaAstro/Transits.jl/pull/23

**Comment by simeonschaub** [comment]
I don't see any fundamental reason, why the simpler version should be slower. think low-hanging fruit to try first would be to see whether just using `@inline` aggressively might be enough to fix this. To see what's making a difference here if that doesn't help, it might also be a good idea to try stepping through the optimized code using Cthulhu.jl and seeing where both are different, it might be something quite simple or perhaps a type assert would help somewhere. I unfortunately don't have time right now to look into this further, but if it's not urgent, I'll probably get to it at some point.
Also note that this is a very artificial benchmark. Deep recursions like that are quite unidiomatic in Julia, since we don't do any TCE, so there is usually a quite significant function call overhead.

**Comment by cscherrer** [comment]
`@inline` is a great idea, that might help,

I agree the deep recursion in the fibonacci example is artificial (but still pretty interesting). But @icweaver was seeing overhead for a single call, and Cthulhu confirms it's not optimizing the "keymap" over a named tuple.

**Comment by mileslucas** [comment]
anecdotally, that sounds similar to what I saw with Cthulhu.jl when we were using aliases with KeywordDispatch.jl- lots of `Any`s due to `NamedTuple` just "giving up" on the keys at the top-level function calls.

**Comment by cscherrer** [comment]
I think we can get there, but it may take some careful tuning. I think I'll try going back to more brute force approach in the short term. If we can get that working, it can at least be a spec and something to benchmark against. 

Once we can get back to `BenchmarkTools.@ballocated` giving zero, we should add this criteria to the tests.

**Comment by cscherrer** [comment]
Might have gotten it. Need to add tests, but here's from the master branch now:
```julia
julia> using KeywordCalls

julia> f(nt::NamedTuple{(:a, :b, :c)}) = nt.a^3 + nt.b^2 + nt.c
f (generic function with 3 methods)

julia> @kwcall f(a,b,c=0)
f (generic function with 3 methods)

julia> @kwalias f [alpha => a]

julia> using BenchmarkTools

julia> @btime $f(a=2,b=4)
  1.182 ns (0 allocations: 0 bytes)
24

julia> @btime $f(alpha=2, b=4)
  1.182 ns (0 allocations: 0 bytes)
24

julia> @btime $f((a=2,b=4))
  1.152 ns (0 allocations: 0 bytes)
24

julia> @btime $f((alpha=2, b=4))
  1.162 ns (0 allocations: 0 bytes)
24

julia> @code_warntype f((alpha=2, b=4))
Variables
  #self#::Core.Const(f)
  nt::NamedTuple{(:alpha, :b), Tuple{Int64, Int64}}

Body::Int64
1 ─ %1 = KeywordCalls._call_in_default_order::Core.Const(KeywordCalls._call_in_default_order)
│   %2 = (:c,)::Core.Const((:c,))
│   %3 = Core.apply_type(Core.NamedTuple, %2)::Core.Const(NamedTuple{(:c,), T} where T<:Tuple)
│   %4 = Core.tuple(0)::Core.Const((0,))
│   %5 = (%3)(%4)::Core.Const((c = 0,))
│   %6 = (KeywordCalls.alias)(Main.f, nt)::NamedTuple{(:a, :b), Tuple{Int64, Int64}}
│   %7 = KeywordCalls.merge(%5, %6)::Core.PartialStruct(NamedTuple{(:c, :a, :b), Tuple{Int64, Int64, Int64}}, Any[Core.Const(0), Int64, Int64])
│   %8 = KeywordCalls._sort(%7)::Core.PartialStruct(NamedTuple{(:a, :b, :c), Tuple{Int64, Int64, Int64}}, Any[Int64, Int64, Core.Const(0)])
│   %9 = (%1)(Main.f, %8)::Int64
└──      return %9
```

**Comment by cscherrer** [comment]
@mileslucas @icweaver can you try this out? If it looks good to you I'll tag a new release

**Comment by cscherrer** [comment]
I added tests for zero allocation. Those are passing on 1.6, but failing on 1.4.

@simeonschaub thanks for suggesting this ought to be possible :)

**Comment by mileslucas** [comment]
cc @icweaver

using `KeywordCalls#master`
```julia
# KeywordCalls.jl
KeplerianOrbit_KC(nt::NamedTuple{(:ρₛ, :Rₛ, :P, :ecc, :t₀, :incl, :Ω, :ω)}) = _KeplerianOrbit(
    nt.ρₛ, nt.Rₛ, nt.P, nt.ecc, nt.t₀, nt.incl, nt.Ω, nt.ω
)
@kwcall KeplerianOrbit_KC(ρₛ, Rₛ, P, ecc=0, t₀=0.0, incl=π/2, Ω=0.0, ω=0.0)
```

```julia
julia> orbit = KeplerianOrbit_KC(ρₛ=2.0, Rₛ=0.5, P=2.0)
  Keplerian Orbit
    a: 3.753076012191651 R⊙
    aRₛ: 7.506152024383302
    b: 4.596192525287218e-16
    ecc: 0.0
    P: 2.0 d
    ρₛ: 0.3386804244486997 M⊙/R⊙³
    Rₛ: 0.5 R⊙
    t₀: 0.0 d
    tₚ: -0.5 d
    t_ref: -0.5 d
    incl: 1.5707963267948966 rad
    Ω: 0.0 rad
    ω: 0.0 rad
    Mₛ: 0.17733265556045136 M⊙
    aₛ: 0.0 R⊙
    Mₚ: 0.0 M⊙
    aₚ: -3.753076012191651 R⊙


julia> @benchmark orbit = KeplerianOrbit_KC(ρₛ=2.0, Rₛ=0.5, P=2.0)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     126.452 ns (0.00% GC)
  median time:      140.545 ns (0.00% GC)
  mean time:        166.972 ns (0.00% GC)
  maximum time:     1.871 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     881
```

---

Seems good to me!

**Comment by icweaver** [comment]
Well I think that confirms it, you all are wizards:

master (current)
```
Project Transits v0.3.5
      Status `~/Projects/Transits.jl/Project.toml`
  [4d827475] KeywordCalls v0.1.5 `https://github.com/cscherrer/KeywordCalls.jl.git#master`
Manual NamedTuple
  83.383 ns (0 allocations: 0 bytes)
KeywordCalls.jl
  83.390 ns (0 allocations: 0 bytes)
KeywordDispatch.jl
  600.715 ns (8 allocations: 640 bytes)

```

master (previous)
```
Project Transits v0.3.5
      Status `~/Projects/Transits.jl/Project.toml`
  [4d827475] KeywordCalls v0.1.5 `https://github.com/cscherrer/KeywordCalls.jl.git#master`
Manual NamedTuple
  83.106 ns (0 allocations: 0 bytes)
KeywordCalls.jl
  3.437 μs (12 allocations: 1.00 KiB)
KeywordDispatch.jl
  598.579 ns (8 allocations: 640 bytes)
```

Thanks so much for all of your amazing work!

**Comment by icweaver** [comment]
haha, @mileslucas beat me to it

**Comment by cscherrer** [comment]
I think there's one last thing, I should have have the allocation tests only run for 1.5 and above
