### ISSUE TITLE
Precompilation weirdness

### ISSUE THREAD

**Issue by cscherrer** [cscherrer/KeywordCalls.jl#13]
There's something strange in the tests.

@mileslucas had this PR:
https://github.com/cscherrer/KeywordCalls.jl/pull/12

I had thought this was passing CI, but maybe I overlooked something, because after merging we're getting
https://github.com/cscherrer/KeywordCalls.jl/runs/2621706487

I think this only has to do with the precompilation tests from @rfourquet , which is especially strange because (1) the PR from Miles doesn't touch those tests, and (2) I don't see how his changes could adversely affect precompilation.

**Comment by simeonschaub** [comment]
Seems pretty clear:
```
ERROR: LoadError: LoadError: Evaluation into the closed module `KeywordCalls` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `KeywordCalls` with `eval` during precompilation - don't do this.
```
Macros should never call `eval`.

**Comment by cscherrer** [comment]
Good catch, thanks @simeonschaub , I had missed that there was an `@eval` in here

**Comment by rfourquet** [comment]
> Macros should never call eval

It's still occasionally pretty useful, but the guideline I think would be that it's fine to eval in the module calling the macro (i.e. `@eval __module__ ...`).

**Comment by simeonschaub** [comment]
It's still a janky solution though, since macros should generally not have side effects.
