### ISSUE TITLE
Multiple `@kwcalls` redefines methods causing warnings

### ISSUE THREAD

**Issue by mileslucas** [cscherrer/KeywordCalls.jl#16]
https://github.com/JuliaAstro/Transits.jl/pull/23#issuecomment-846185815

Calling `@kwcall` multiple times on the same method name will create warnings in module code. This is happening because https://github.com/cscherrer/KeywordCalls.jl/blob/96b14dc43afc29b7a2299e2001b67985464cfd8e/src/KeywordCalls.jl#L39-L43 adds the two `foo(::NamedTuple)` and `foo(; kwargs...)` calls, regardless if they exist already.

**Comment by mileslucas** [comment]
Could this be handled with `hasmethod`?
```julia
q = quote
    KeywordCalls._call_in_default_order(::typeof($f), nt::NamedTuple{($(sorted_args...),)}) = $f(NamedTuple{($(args...),)}(nt))
	if !hasmethod($f, Tuple{NamedTuple})
	    $f(nt::NamedTuple) = KeywordCalls._call_in_default_order($f, _sort(merge($defaults, $alias($f, nt))))
	end
	if !hasmethod($f, Tuple{})
	    $f(; kw...) = $f(merge($defaults, $alias($f, NamedTuple(kw))))
	end
end
```

**Comment by cscherrer** [comment]
Thanks for catching this! This seems like the right idea. Let's see if we can do this with the `hasmethod` checks outside the quote, roughly like

```julia
q = quote
    KeywordCalls._call_in_default_order(::typeof($f), nt::NamedTuple{($(sorted_args...),)}) = $f(NamedTuple{($(args...),)}(nt))
end

if !hasmethod(f, Tuple{NamedTuple})
    push!(q.args, :($f(nt::NamedTuple) = KeywordCalls._call_in_default_order($f, _sort(merge($defaults, $alias($f, nt)))))
end

if !hasmethod(f, Tuple{})
    push!(q.args, :($f(; kw...) = $f(merge($defaults, $alias($f, NamedTuple(kw)))))
end
```
If we need the `hasmethod` in the generated code, we can try `static_hasmethod` from [Tricks.jl](https://github.com/oxinabox/Tricks.jl)
